# hardware-configuration.nix - Hardware-specific configuration
# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
# Please make changes to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Kernel modules available in initial ramdisk
  boot.initrd.availableKernelModules = [
    "xhci_pci"    # USB 3.0 controller
    "ahci"        # SATA controller
    "usb_storage" # USB storage devices
    "usbhid"      # USB HID devices
    "sd_mod"      # SCSI disk support
    "sdhci_pci"   # SD host controller
  ];

  boot.initrd.kernelModules = [ ];  # Additional initrd kernel modules
  boot.kernelModules = [ "kvm-intel" ];  # Kernel modules to load
  boot.extraModulePackages = [ ];  # Additional kernel module packages

  # Root filesystem configuration
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5023eb8a-6c32-492d-b866-dc71d0f68aa8";
    fsType = "ext4";
  };

  # Boot filesystem configuration (UEFI)
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CBF0-45ED";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];  # Secure permissions
  };

  # Swap device configuration
  swapDevices = [
    { device = "/dev/disk/by-uuid/8df43943-127d-4c27-bb07-46696faa3a31"; }
  ];

  # Networking configuration
  # Enable DHCP on each ethernet and wireless interface
  networking.useDHCP = lib.mkDefault true;

  # Optional: Explicit per-interface DHCP configuration
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  # System architecture and platform
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Intel CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault
    config.hardware.enableRedistributableFirmware;
}
