# =====================================
# HARDWARE CONFIGURATION (AUTO-GENERATED)
# =====================================
# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")  # Hardware auto-detection
  ];

  # =====================================
  # KERNEL MODULES FOR BOOT
  # =====================================
  boot.initrd.availableKernelModules = [
    "xhci_pci"    # USB 3.0 controller
    "ahci"        # SATA controller
    "usb_storage" # USB storage devices
    "usbhid"      # USB input devices
    "sd_mod"      # SCSI disk support
    "sdhci_pci"   # SD host controller
  ];
  boot.initrd.kernelModules = [ ];  # Additional initrd modules
  boot.kernelModules = [ "kvm-intel" ];  # Intel KVM virtualization
  boot.extraModulePackages = [ ];   # Additional kernel module packages

  # =====================================
  # FILESYSTEM MOUNT POINTS
  # =====================================
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b709d8da-ba9c-4759-b0c9-39594b862071";
    fsType = "ext4";  # Root filesystem type
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8B8E-6527";
    fsType = "vfat";  # EFI system partition
    options = [ "fmask=0022" "dmask=0022" ];  # File and directory permissions
  };

  # =====================================
  # SWAP CONFIGURATION
  # =====================================
  swapDevices = [
    {
      device = "/dev/disk/by-uuid/ad324a1b-e6d2-4e2e-ace7-997df0b83307";
    }
  ];

  # =====================================
  # NETWORKING CONFIGURATION
  # =====================================
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;  # Use DHCP for all interfaces
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;  # Ethernet (commented)
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;  # Wireless (commented)

  # =====================================
  # PLATFORM AND FIRMWARE
  # =====================================
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";  # System architecture
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
